Fix bug where valuation changed manually bubbles up to next package c…
crossroads/stock.goodcity pull request #968
Opened 2020-12-10 04:30 UTC by bharat619

### Ticket Link: 
https://jira.crossroads.org.hk/browse/GCW-3439

### What does this PR do?
- Resolves bug of valuation taking from previous package creation
- Resolve preload dependency problem

2020-12-10 05:46 UTC, shreyas098 approved these changes

2020-12-11 05:48 UTC, patrixr commented on app/components/goodcity/code-search-overlay.js
> -
do sync up with @abulsayyad123 
I think he touched this in his own PR

2020-12-11 05:50 UTC, patrixr requested changes

2020-12-11 05:50 UTC, patrixr commented on app/services/package-type-service.js
> -
I believe this is used in the Stocktake route. Please make a search on the whole project and make sure there's no call to that function

2020-12-15 04:13 UTC, patrixr approved these changes

2020-12-15 04:22 UTC, merged